apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-configmap-secret.yaml
  - 01-rabbitmq-deployment-service.yaml
  - 02-producer-deployment.yaml
  - 03-consumer-deployment.yaml